minVersion: "0.18.0"
github:
  owner: getsentry
  repo: rb
changelog: CHANGES
changelogPolicy: auto
statusProvider:
  name: github
artifactProvider:
  name: github
targets:
  - name: pypi
  - name: github
  - name: sentry-pypi
    internalPypiRepo: getsentry/pypi

requireNames:
  - /^rb-.+-py2.py3-none-any.whl$/
