language: python

sudo: false

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: pypy
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=2.7.10
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin:$PYENV_ROOT/versions/2.7.10/bin
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=pypy-2.6.0
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin:$PYENV_ROOT/versions/pypy-2.6.0/bin

install:
  - bash .travis-${TRAVIS_OS_NAME}.sh
  - pip install --upgrade pip
  - pip install pytest
  - pip install --editable .

script:
  - make test
