language: python
dist: xenial
os: linux

jobs:
  include:
    - python: 2.7
      env: REDIS_VERSION=">=2.6,<2.11"
    - python: 2.7
      env: REDIS_VERSION=">=3.3,<3.4"
    - python: pypy
    - python: 3.6
      env: REDIS_VERSION=">=2.6,<2.11"
    - python: 3.6
      env: REDIS_VERSION=">=3.3,<3.4"
    - python: 3.8
    - python: pypy3
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=2.7.10
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin:$PYENV_ROOT/versions/2.7.10/bin
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=3.6.10
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin:$PYENV_ROOT/versions/3.6.10/bin

install:
  - bash .travis-${TRAVIS_OS_NAME}.sh
  - pip install --upgrade pip
  - pip install pytest
  - pip install --editable .

script:
  - make test
