name: build

on:
  push:
    branches:
      - master
      - release/**

jobs:
  dist:
    name: Wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: |
          pip install wheel
          python setup.py bdist_wheel
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: dist/*
