name: test

on:
  push:
    branches:
      - master
      - release/**
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.8", "3.9", "3.10", "pypy-3.8"]
        REDIS_VERSION: ["<3", "<4"]
    env:
      REDIS_VERSION: ${{ matrix.REDIS_VERSION }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install --editable .
      - name: Install Redis
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update && sudo apt install redis-server --no-install-recommends -y
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install --quiet redis
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi
      - name: Run tests
        run: |
          make test
  collector:
    needs: [test]
    if: always()
    runs-on: ubuntu-22.04
    steps:
      - name: Check for failures
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1
